### PR TITLE
fix: optimize foreign key access in a join relevant path

### LINKED ISSUE #479: Two step association path to foreign key not correctly translated
```cds
entity Classroom {
  key ID: Integer;
  pupils: Association to many ClassRoomPupil on pupils.classroom = $self
}

entity Pupil {
  key ID: Integer;
  classroom: Association to many ClassRoomPupil on classroom.pupil = $self
}

entity ClassRoomPupil {
  key classroom: Association to Classroom;
  key pupil: Association to Pupil;
}
```

1. `cds repl`
2. bootstrap server
 

3.  query: `SELECT.columns('count(pupils.pupil.ID) as studentCount').from(Classroom).where('ID = 1').forSql()`

```js
Query {
  SELECT: {
    columns: [
      {
        func: 'count',
        args: [ { ref: [ 'pupil', 'ID' ] } ], // there is no pupil alias
        as: 'studentCount'
      }
    ],
    from: {
      join: 'left',
      args: [
        { ref: [ 'sap.capire.bookshop.Classroom' ], as: 'Classroom' },
        { ref: [ 'sap.capire.bookshop.ClassRoomPupil' ], as: 'pupils' }
      ],
      on: [
        { ref: [ 'pupils', 'classroom_ID' ] },
        '=',
        { ref: [ 'Classroom', 'ID' ] }
      ]
    },
    where: [ { ref: [ 'Classroom', 'ID' ] }, '=', { val: 1 } ]
  }
}
```
→ Should be `pupils.pupil_ID`

---

some data:

```js
// Insert data into Classroom table
await INSERT({ ID: 1, name: 'Math Class' }).into(Classroom);
await INSERT({ ID: 2, name: 'Science Class' }).into(Classroom);
await INSERT({ ID: 3, name: 'History Class' }).into(Classroom);

// Insert data into Pupil table
await INSERT({ ID: 101, name: 'John Smith' }).into(Pupil);
await INSERT({ ID: 102, name: 'Emma Johnson' }).into(Pupil);
await INSERT({ ID: 103, name: 'Michael Brown' }).into(Pupil);
await INSERT({ ID: 104, name: 'Sophia Martinez' }).into(Pupil);

// Insert data into ClassRoomPupil table (assigning pupils to classrooms)
await INSERT({ classroom_ID: 1, pupil_ID: 101 }).into(ClassRoomPupil); // John Smith in Math Class
await INSERT({ classroom_ID: 1, pupil_ID: 102 }).into(ClassRoomPupil); // Emma Johnson in Math Class
await INSERT({ classroom_ID: 2, pupil_ID: 103 }).into(ClassRoomPupil); // Michael Brown in Science Class
await INSERT({ classroom_ID: 3, pupil_ID: 104 }).into(ClassRoomPupil); // Sophia Martinez in History Class
```

### PR DESCRIPTION
**Pull request by patricebender**
if the path resolves to a foreign key, we should not create a join for the last association, instead we shortcut to the foreign key. This was not considered for join relevant paths. 

fix #479

### CODE REVIEW

File: db-service/lib/cqn4sql.js [hunk 1]
```diff
@@ -2080,6 +2076,31 @@ module.exports = Object.assign(cqn4sql, {
   notSupportedOps,
 })
 
+function calculateElementName(token) {
+  const nonJoinRelevantAssoc = [...token.$refLinks].findIndex(l => l.definition.isAssociation && l.onlyForeignKeyAccess)
+  let name
```
Comment (BobdenOs) [inline db-service/lib/cqn4sql.js:2081]: Looks like some left over, but should work.

**Review by BobdenOs — APPROVED** [review]
looks good

**Review by stewsk — COMMENTED** [review]
you could maybe add
```cds
// test that no optimization is done if a filter is applied

SELECT from ClassRoomPupil {
      classroom[name = 'Firenze'].ID
    }

// test what happens if both an optimizable and a non-optimizable path are present

SELECT from ClassRoomPupil {
      classroom.ID,
      classroom.name
    }

// variation of previous test

SELECT from ClassRoomPupil {
      classroom.ID,
      classroom[name = 'Firenze'].ID as ID2
    }
```
