### PR TITLE
fix: consider `nulls first | last` on `orderBy`

### LINKED ISSUE #1062: `NULLS first | last` is not rendered to sql
When defining `null first | last` on `order by`, `cqn2sql` does not yield the sorting modifier.

```js
> q = SELECT.from(Authors).columns('name', 'dateOfDeath') .orderBy`dateOfDeath asc nulls first`
cds.ql {
  SELECT: {
    from: { ref: [ 'sap.capire.bookshop.Authors' ] },
    columns: [ { ref: [ 'name' ] }, { ref: [ 'dateOfDeath' ] } ],
    orderBy: [ { ref: [ 'dateOfDeath' ], sort: 'asc', nulls: 'first' } ]
  }
}
> q.forSQL()
cds.ql {
  SELECT: {
    from: { ref: [ 'sap.capire.bookshop.Authors' ], as: 'Authors' },
    columns: [
      { ref: [ 'Authors', 'name' ] },
      { ref: [ 'Authors', 'dateOfDeath' ] }
    ],
    orderBy: [ { ref: [ 'dateOfDeath' ], sort: 'asc', nulls: 'first' } ]
  }
}
> q.toSQL()
{
  sql: `
SELECT
    json_insert(
        '{}',
        '$."name"',
        name,
        '$."dateOfDeath"',
        dateOfDeath
    ) as _json_
FROM
    (
        SELECT
            Authors.name,
            Authors.dateOfDeath as dateOfDeath
        FROM
            sap_capire_bookshop_Authors as Authors
        ORDER BY
            dateOfDeath ASC
    )
`,
  values: []
}
```

### PR DESCRIPTION
**Pull request by patricebender**
fix #1062

### CODE REVIEW

File: db-service/lib/cqn2sql.js [hunk 1]
```diff
@@ -421,14 +421,15 @@ class CQN2SQLRenderer {
...
-          this.expr(c) +
+    return orderBy.map(c => {
+      const o = localized
+        ? this.expr(c) +
           (c.element?.[this.class._localized] ? ' COLLATE NOCASE' : '') +
           (c.sort?.toLowerCase() === 'desc' || c.sort === -1 ? ' DESC' : ' ASC')
-        : c => this.expr(c) + (c.sort?.toLowerCase() === 'desc' || c.sort === -1 ? ' DESC' : ' ASC'),
-    )
+        : this.expr(c) + (c.sort?.toLowerCase() === 'desc' || c.sort === -1 ? ' DESC' : ' ASC')
+      if (c.nulls) return o + ' NULLS ' + c.nulls
```
Comment (BobdenOs) [inline db-service/lib/cqn2sql.js:430]: I would make this a little bit more strict. As this way people could put what ever they want into the `SQL`. Which generally is seen as bad thing and might even get called `SQL injection`.

Comment (patricebender) [reply db-service/lib/cqn2sql.js:430]: absolutely 💯

**Review by BobdenOs — APPROVED** [review]
